### ISSUE TITLE
NPM version doesn't work

### ISSUE THREAD

**Issue by puckey** [dannav/directory-tree-promise#2]
```
Error: Cannot find module 'babel-runtime/core-js/object/keys'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/data-api/node_modules/directory-tree-promise/dist/directory-tree.js:3:13)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

**Comment by dannav** [comment]
Can you tell me if installing babel-runtime addresses your issue?
